version: 2
jobs:
  build:
    docker:
      - image: docker:git
      - image: redis:alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Docker volumes
          command: |
            docker create --name input --volume /home/builder/package alpine:3.6 /bin/true
            docker create --name output --volume /packages alpine:3.6 /bin/true
            docker cp ./APKBUILD input:/home/builder/package
      - run:
          name: Build packages
          command: |
            docker run --env RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" --env RSA_PRIVATE_KEY_NAME="sgerrand.rsa" \
                       --volumes-from input --volumes-from output sgerrand/alpine-abuild:v5
      - run:
          name: Extract packages
          command: |
            mkdir -p packages
            docker cp output:/packages/builder packages/
      - run:
          name: Test installing packages
          command: |
            cp sgerrand.rsa.pub /etc/apk/keys/sgerrand.rsa.pub
            apk add --no-progress --update-cache --upgrade ./packages/builder/x86_64/php5-redis-*.apk
      - run:
          name: Test PHP module
          command: |
             apk add --no-cache --no-progress php5-cli
             php5 -r '$redis = new Redis(); var_dump($redis->connect("127.0.0.1"));' | grep 'bool(true)'
      - run:
          name: Remove Docker volumes
          command: |
            docker rm input
            docker rm output
          when: always
      - store_artifacts:
          destination: pkgs
          path: packages
      - persist_to_workspace:
          root: .
          paths:
            - packages
    working_directory: ~/alpine-pkg-php5-redis
  release-master:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease -delete unreleased packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease unreleased packages/builder/x86_64
    working_directory: ~/alpine-pkg-php5-redis
  release-tag:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages/builder/x86_64
    working_directory: ~/alpine-pkg-php5-redis
workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - release-master:
          requires:
            - build
          filters:
            branches:
              only: master
      - release-tag:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){1,2}(\-r\d+)?$/
